// Comprehensive list of interests with emojis and categories (from Muzz)
export const INTEREST_CATEGORIES = {
  Sport: [
    { value: "American football", emoji: "🏈" },
    { value: "Archery", emoji: "🏹" },
    { value: "Badminton", emoji: "🏸" },
    { value: "Baseball", emoji: "⚾" },
    { value: "Basketball", emoji: "🏀" },
    { value: "Boxing", emoji: "🥊" },
    { value: "Calisthenics", emoji: "💪" },
    { value: "Cricket", emoji: "🏏" },
    { value: "Cycling", emoji: "🚴" },
    { value: "Dancing", emoji: "💃" },
    { value: "Fencing", emoji: "🤺" },
    { value: "Figure skating", emoji: "⛸️" },
    { value: "Golf", emoji: "⛳" },
    { value: "Gym", emoji: "🏋️" },
    { value: "Gymnastics", emoji: "🤸" },
    { value: "Horse riding", emoji: "🏇" },
    { value: "Ice hockey", emoji: "🏒" },
    { value: "Mixed martial arts", emoji: "🥋" },
    { value: "Motorsports", emoji: "🏎️" },
    { value: "Pilates", emoji: "🧘" },
    { value: "Rock climbing", emoji: "🧗" },
    { value: "Rollerblading", emoji: "🛼" },
    { value: "Rowing", emoji: "🚣" },
    { value: "Rugby", emoji: "🏉" },
    { value: "Running", emoji: "🏃" },
    { value: "Sailing", emoji: "⛵" },
    { value: "Skateboarding", emoji: "🛹" },
    { value: "Skiing", emoji: "⛷️" },
    { value: "Snowboarding", emoji: "🏂" },
    { value: "Soccer", emoji: "⚽" },
    { value: "Surfing", emoji: "🏄" },
    { value: "Swimming", emoji: "🏊" },
    { value: "Tennis", emoji: "🎾" },
    { value: "Volleyball", emoji: "🏐" },
    { value: "Yoga", emoji: "🧘" },
  ],
  Food: [
    { value: "Baking", emoji: "🧁" },
    { value: "Cooking", emoji: "👨‍🍳" },
    { value: "Coffee", emoji: "☕" },
    { value: "Tea", emoji: "🍵" },
    { value: "Wine tasting", emoji: "🍷" },
    { value: "Foodie", emoji: "🍽️" },
    { value: "Vegan cooking", emoji: "🥗" },
    { value: "BBQ", emoji: "🍖" },
  ],
  Creative: [
    { value: "Art", emoji: "🎨" },
    { value: "Photography", emoji: "📷" },
    { value: "Writing", emoji: "✍️" },
    { value: "Poetry", emoji: "📝" },
    { value: "Music", emoji: "🎵" },
    { value: "Singing", emoji: "🎤" },
    { value: "Playing instrument", emoji: "🎸" },
    { value: "Drawing", emoji: "✏️" },
    { value: "Painting", emoji: "🖌️" },
    { value: "Crafts", emoji: "🧵" },
    { value: "DIY", emoji: "🔨" },
    { value: "Fashion", emoji: "👗" },
    { value: "Design", emoji: "📐" },
  ],
  Entertainment: [
    { value: "Movies", emoji: "🎬" },
    { value: "TV shows", emoji: "📺" },
    { value: "Netflix", emoji: "🍿" },
    { value: "Theater", emoji: "🎭" },
    { value: "Comedy", emoji: "😂" },
    { value: "Stand-up comedy", emoji: "🎤" },
    { value: "Concerts", emoji: "🎵" },
    { value: "Festivals", emoji: "🎪" },
    { value: "Board games", emoji: "🎲" },
    { value: "Video games", emoji: "🎮" },
    { value: "Gaming", emoji: "🕹️" },
  ],
  Outdoors: [
    { value: "Hiking", emoji: "🥾" },
    { value: "Camping", emoji: "⛺" },
    { value: "Travel", emoji: "✈️" },
    { value: "Beach", emoji: "🏖️" },
    { value: "Nature", emoji: "🌳" },
    { value: "Gardening", emoji: "🌱" },
    { value: "Fishing", emoji: "🎣" },
    { value: "Picnics", emoji: "🧺" },
  ],
  Intellectual: [
    { value: "Reading", emoji: "📚" },
    { value: "Learning languages", emoji: "🗣️" },
    { value: "History", emoji: "📜" },
    { value: "Science", emoji: "🔬" },
    { value: "Politics", emoji: "🗳️" },
    { value: "Philosophy", emoji: "🤔" },
    { value: "Astronomy", emoji: "🔭" },
    { value: "Podcasts", emoji: "🎧" },
  ],
  Social: [
    { value: "Volunteering", emoji: "🤝" },
    { value: "Charity work", emoji: "❤️" },
    { value: "Community service", emoji: "👥" },
    { value: "Socializing", emoji: "🗣️" },
    { value: "Networking", emoji: "🤝" },
  ],
  Wellness: [
    { value: "Meditation", emoji: "🧘" },
    { value: "Mindfulness", emoji: "☮️" },
    { value: "Self-care", emoji: "💆" },
    { value: "Spa", emoji: "🛀" },
    { value: "Wellness", emoji: "🌸" },
  ],
  Islamic: [
    { value: "Quran reading", emoji: "📖" },
    { value: "Islamic studies", emoji: "📚" },
    { value: "Mosque activities", emoji: "🕌" },
    { value: "Islamic history", emoji: "📜" },
    { value: "Arabic language", emoji: "🗣️" },
  ],
};

// Flatten all interests for easy selection
export const ALL_INTERESTS = Object.entries(INTEREST_CATEGORIES).flatMap(
  ([category, interests]) =>
    interests.map((interest) => ({ ...interest, category }))
);

// Comprehensive profession list (from Muzz)
export const PROFESSIONS = [
  "Accountant",
  "Acting Professional",
  "Actor",
  "Administration Employee",
  "Administration Professional",
  "Advertising Professional",
  "Air Hostess",
  "Architect",
  "Armed Forces Employee",
  "Art & Design Employee",
  "Artisan",
  "Artist",
  "Baker",
  "Banker",
  "Barber/Hairstylist",
  "Beautician",
  "Business Owner",
  "Chef",
  "Chemist",
  "Civil Servant",
  "Consultant",
  "Customer Service",
  "Dentist",
  "Designer",
  "Developer",
  "Doctor",
  "Driver",
  "Educator",
  "Engineer",
  "Entrepreneur",
  "Fashion Designer",
  "Finance Professional",
  "Firefighter",
  "Flight Attendant",
  "Government Employee",
  "Graphic Designer",
  "Healthcare Professional",
  "HR Professional",
  "IT Professional",
  "Journalist",
  "Lawyer",
  "Lecturer",
  "Librarian",
  "Manager",
  "Marketing Professional",
  "Mechanic",
  "Media Professional",
  "Medical Professional",
  "Musician",
  "Nurse",
  "Paramedic",
  "Pharmacist",
  "Photographer",
  "Physician",
  "Pilot",
  "Police Officer",
  "Professor",
  "Programmer",
  "Project Manager",
  "Real Estate Agent",
  "Researcher",
  "Retail Employee",
  "Sales Professional",
  "Scientist",
  "Security Officer",
  "Social Worker",
  "Software Engineer",
  "Student",
  "Surgeon",
  "Teacher",
  "Technician",
  "Therapist",
  "Translator",
  "Unemployed",
  "Veterinarian",
  "Writer",
  "Other",
];

// Height options in cm and feet/inches
export const HEIGHT_OPTIONS_CM = [
  { cm: 122, ft: "4'0\"" },
  { cm: 124, ft: "4'1\"" },
  { cm: 127, ft: "4'2\"" },
  { cm: 130, ft: "4'3\"" },
  { cm: 132, ft: "4'4\"" },
  { cm: 135, ft: "4'5\"" },
  { cm: 137, ft: "4'6\"" },
  { cm: 140, ft: "4'7\"" },
  { cm: 142, ft: "4'8\"" },
  { cm: 145, ft: "4'9\"" },
  { cm: 147, ft: "4'10\"" },
  { cm: 150, ft: "4'11\"" },
  { cm: 152, ft: "5'0\"" },
  { cm: 155, ft: "5'1\"" },
  { cm: 157, ft: "5'2\"" },
  { cm: 160, ft: "5'3\"" },
  { cm: 163, ft: "5'4\"" },
  { cm: 165, ft: "5'5\"" },
  { cm: 168, ft: "5'6\"" },
  { cm: 170, ft: "5'7\"" },
  { cm: 173, ft: "5'8\"" },
  { cm: 175, ft: "5'9\"" },
  { cm: 178, ft: "5'10\"" },
  { cm: 180, ft: "5'11\"" },
  { cm: 183, ft: "6'0\"" },
  { cm: 185, ft: "6'1\"" },
  { cm: 188, ft: "6'2\"" },
  { cm: 191, ft: "6'3\"" },
  { cm: 193, ft: "6'4\"" },
  { cm: 196, ft: "6'5\"" },
  { cm: 198, ft: "6'6\"" },
  { cm: 201, ft: "6'7\"" },
  { cm: 203, ft: "6'8\"" },
];

// Sect options with detailed breakdown
export const SECT_OPTIONS = [
  "No preference",
  "Sunni",
  "Sunni (Hanafi)",
  "Sunni (Maliki)",
  "Sunni (Shafi)",
  "Sunni (Hanbali)",
  "Shia",
  "Shia (Twelver)",
  "Shia (Ismaili)",
  "Shia (Zaydi)",
  "Sufi",
  "Other",
];

// Religious practice levels
export const RELIGIOUS_PRACTICE_OPTIONS = [
  {
    value: "Strictly practising",
    description: "I pray all the time, fast, and adhere strictly to Islamic tenets",
  },
  {
    value: "Actively practising",
    description: "I try and make religious practice part of my daily life where I can",
  },
  {
    value: "Occasionally practising",
    description: "I only practise during Ramadan/Eid and other special occasions",
  },
  {
    value: "Not practising at all",
    description: "I'm culturally a Muslim but do not actively practice",
  },
];

// Marital status options
export const MARITAL_STATUS_OPTIONS = [
  "Never married",
  "Separated",
  "Divorced",
  "Annulled",
  "Widowed",
  "Married",
];

// Personality traits (from Muzz - select up to 5)
export const PERSONALITY_TRAITS = [
  { value: "Active Listener", emoji: "👂" },
  { value: "Adventurous", emoji: "🧗" },
  { value: "Affectionate", emoji: "🥰" },
  { value: "Ambitious", emoji: "🎯" },
  { value: "Animal lover", emoji: "🐾" },
  { value: "Assertive", emoji: "💪" },
  { value: "Bookworm", emoji: "🐛" },
  { value: "Brunch Lover", emoji: "🥐" },
  { value: "Carefree", emoji: "😌" },
  { value: "Charismatic", emoji: "😎" },
  { value: "Cheerful", emoji: "😊" },
  { value: "Competitive", emoji: "💪" },
  { value: "Confident", emoji: "😤" },
  { value: "Conservative", emoji: "🕊️" },
  { value: "Creative", emoji: "🎨" },
  { value: "Cultural", emoji: "🏛️" },
  { value: "ENFJ", emoji: "🧠" },
  { value: "ENFP", emoji: "🧠" },
  { value: "ENTJ", emoji: "🧠" },
  { value: "ENTP", emoji: "🧠" },
  { value: "ESFJ", emoji: "🧠" },
  { value: "ESFP", emoji: "🧠" },
  { value: "ESTJ", emoji: "🧠" },
  { value: "ESTP", emoji: "🧠" },
  { value: "Empathetic", emoji: "❤️" },
  { value: "Entrepreneurial", emoji: "💼" },
  { value: "Extroverted", emoji: "🗣️" },
  { value: "Family-oriented", emoji: "👨‍👩‍👧‍👦" },
  { value: "Fashionable", emoji: "👔" },
  { value: "Funny", emoji: "😂" },
  { value: "Generous", emoji: "🤲" },
  { value: "Germaphobe", emoji: "🧼" },
  { value: "Good with Kids", emoji: "👶" },
  { value: "INFJ", emoji: "🧠" },
  { value: "INFP", emoji: "🧠" },
  { value: "INTJ", emoji: "🧠" },
  { value: "INTP", emoji: "🧠" },
  { value: "ISFJ", emoji: "🧠" },
  { value: "ISFP", emoji: "🧠" },
  { value: "ISTJ", emoji: "🧠" },
  { value: "ISTP", emoji: "🧠" },
  { value: "Intelligent", emoji: "🤓" },
  { value: "Introverted", emoji: "🧘" },
  { value: "Liberal", emoji: "🕊️" },
  { value: "Nerdy", emoji: "🤓" },
  { value: "Organized", emoji: "📋" },
  { value: "Outdoorsy", emoji: "🌲" },
  { value: "Patient", emoji: "⏳" },
  { value: "Romantic", emoji: "💝" },
  { value: "Sarcastic", emoji: "😏" },
  { value: "Spontaneous", emoji: "🎲" },
  { value: "Traditional", emoji: "🏺" },
];

// Ethnicity options (from Muzz - multi-select)
export const ETHNICITY_OPTIONS = [
  "No preference",
  "Afghan",
  "African American",
  "Arab",
  "Azeri",
  "Bangladeshi",
  "Caribbean",
  "Central African",
  "Central Asian",
  "Circassian",
  "East African",
  "East Asian",
  "Egyptian",
  "European",
  "Indian",
  "Kurdish",
  "Lebanese",
  "Mixed",
  "Moroccan",
  "North African",
  "Pakistani",
  "Palestinian",
  "Persian",
  "Somali",
  "South Asian",
  "Southeast Asian",
  "Syrian",
  "Turkish",
  "West African",
  "Other",
];

// Education level options (from Muzz - expanded)
export const EDUCATION_OPTIONS = [
  "Secondary school",
  "Some college",
  "Bachelors",
  "Masters",
  "Doctorate",
  "Trade school",
  "Prefer not to say",
];
